-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
        args:
        - -i
        - --ignore=E309,E501
    -   id: check-added-large-files
        language_version: python3
    -   id: check-byte-order-marker
        language_version: python3
    -   id: check-json
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: fix-encoding-pragma
        language_version: python3
        args:
        - --remove
    -   id: flake8
        language_version: python3
    -   id: name-tests-test
        language_version: python3
    -   id: trailing-whitespace
        language_version: python3
    -   id: requirements-txt-fixer
        language_version: python3
        files: requirements-dev.txt
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.0.0
    hooks:
    -   id: pyupgrade
        language_version: python3
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3
        args: [
            '--remove-import', 'from __future__ import absolute_import',
            '--remove-import', 'from __future__ import print_function',
            '--remove-import', 'from __future__ import unicode_literals',
        ]
