language: python

matrix:
  include:
  - env: TOXENV=py35
    # Ensure one test with a python version that does not support aiohttp>=3
    python: "3.5.2"
  - env: TOXENV=py35
    python: "3.5"
  - env: TOXENV=py36
    python: "3.6"
  - env: TOXENV=pre-commit
    python: "3.6"

install:
- "pip install tox coveralls"
script:
- tox -e $TOXENV
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
